POST /goform/goform_get_cmd_process HTTP/1.1
Host: 192.168.0.1
Accept: application/json, text/javascript, */*; q=0.01
Referer: http://192.168.0.1/index.html

cmd=sms_data_total&page=0&data_per_page=500&mem_store=1&tags=10&order_by=order+by+id+desc&_={{$timestamp}}